### PR TITLE
Improve tests

### PR DESCRIPTION
**Pull request by mikaoelitiana**
- ignore coverate folder in `.gitignore`
- simulate clicks on previous and next arrows

### CODE REVIEW

**Comment by mikaoelitiana** [comment]
Code coverage BEFORE 

capture d ecran 2018-10-01 a 18 22 53

**Comment by mikaoelitiana** [comment]
Code coverage AFTER

capture d ecran 2018-10-01 a 19 04 34

**Comment by gabrielbs** [comment]
Thanksss!

**Comment by mikaoelitiana** [comment]
My pleasure.

**Pull request merged**
